[project]
name = "ankifier"
version = "0.1.0"
description = ""
authors = [
    {name = "Enes Aydogan",email = "enes35ihsan@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "mistralai (>=1.0.0,<2.0.0)",
    "elevenlabs (>=1.0.0,<2.0.0)",
    "requests (>=2.31.0,<3.0.0)",
    "fastapi (>=0.115.0,<1.0.0)",
    "uvicorn[standard] (>=0.30.0,<1.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
]

[tool.poetry]
packages = [
    {include = "ankifier", from = "src"},
]

[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"

[project.scripts]
ankifier = "ankifier.api:run"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
